inherit_gem:
  rubocop_defaults: .rubocop.yml

require:
  - rubocop/cop/internal_affairs

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/FileName:
 Exclude:
   - lib/rubocop-sidekiq.rb

RSpec/ExampleLength:
  Max: 10

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
