inherit_gem:
  rubocop_defaults: .rubocop.yml

require:
  - rubocop/cop/internal_affairs
  - ./lib/rubocop/cop/internal_affairs/incorrect_example_description

AllCops:
  NewCops: enable

InternalAffairs/IncorrectExampleDescription:
  Include:
    - spec/**/*.rb
  Strict: false
  PositiveDescriptions:
    - registers an offense
    - registers an offense and corrects
    - registers multiple offenses

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/ClassLength:
  Exclude:
  - lib/rubocop/cop/sidekiq/active_record_argument.rb

Naming/FileName:
 Exclude:
   - lib/rubocop-sidekiq.rb

RSpec/ExampleLength:
  Max: 10

Style/CaseLikeIf:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
