# This is the default configuration file.

Sidekiq/ActiveRecordArgument:
  Description: "ActiveRecord arguments are not valid parameters to a Sidekiq worker"
  Enabled: true
  VersionAdded: '0.5'

Sidekiq/ConstArgument:
  Description: "Classes and objects are not valid parameters to a Sidekiq worker"
  Enabled: true
  VersionAdded: '0.5'

Sidekiq/DateTimeArgument:
  Description: "Use strings or integers to represent dates/times, not objects"
  Enabled: true
  VersionAdded: '0.5'

Sidekiq/KeywordArguments:
  Description: "Do not use keyword arguments in a sidekiq worker's perform method"
  Enabled: true
  VersionAdded: '0.5'

Sidekiq/SymbolArgument:
  Description: 'Use strings instead of symbols as parameters to a worker'
  Enabled: true
  VersionAdded: '0.5'

